
package org.tarjeta.digital.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TarjetaService", targetNamespace = "http://service.digital.tarjeta.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TarjetaService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "eliminarTarjeta", targetNamespace = "http://service.digital.tarjeta.org/", className = "org.tarjeta.digital.service.EliminarTarjeta")
    @ResponseWrapper(localName = "eliminarTarjetaResponse", targetNamespace = "http://service.digital.tarjeta.org/", className = "org.tarjeta.digital.service.EliminarTarjetaResponse")
    public void eliminarTarjeta(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<org.tarjeta.digital.service.Tarjeta>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerTodas", targetNamespace = "http://service.digital.tarjeta.org/", className = "org.tarjeta.digital.service.ObtenerTodas")
    @ResponseWrapper(localName = "obtenerTodasResponse", targetNamespace = "http://service.digital.tarjeta.org/", className = "org.tarjeta.digital.service.ObtenerTodasResponse")
    public List<Tarjeta> obtenerTodas();

    /**
     * 
     * @param arg0
     * @return
     *     returns org.tarjeta.digital.service.Tarjeta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerTarjeta", targetNamespace = "http://service.digital.tarjeta.org/", className = "org.tarjeta.digital.service.ObtenerTarjeta")
    @ResponseWrapper(localName = "obtenerTarjetaResponse", targetNamespace = "http://service.digital.tarjeta.org/", className = "org.tarjeta.digital.service.ObtenerTarjetaResponse")
    public Tarjeta obtenerTarjeta(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.tarjeta.digital.service.Tarjeta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "creartargeta", targetNamespace = "http://service.digital.tarjeta.org/", className = "org.tarjeta.digital.service.Creartargeta")
    @ResponseWrapper(localName = "creartargetaResponse", targetNamespace = "http://service.digital.tarjeta.org/", className = "org.tarjeta.digital.service.CreartargetaResponse")
    public Tarjeta creartargeta(
        @WebParam(name = "arg0", targetNamespace = "")
        Tarjeta arg0);

}
